name: best_diplomats
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1
  google_fonts: ^8.0.1
  animate_do: ^4.2.0
  flutter_svg: ^2.0.10+1
  get_it: ^9.2.0
  shared_preferences: ^2.2.3
  animated_text_kit: ^4.3.0
  video_player: ^2.10.1
  url_launcher: ^6.3.2
  chewie: ^1.8.0
  supabase_flutter: ^2.6.0
  image_picker: ^1.2.1
  country_picker: ^2.0.27
  intl_phone_field: ^3.2.0
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_face_detection: ^0.13.2
  camera: ^0.11.3+1
  mrz_parser: ^2.0.1
  image: ^4.7.2
  permission_handler: ^12.0.1
  responsive_framework: ^1.1.1
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/imagesUi/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagesUi/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/imagesUi/logo.png"
